# This is a basic workflow to help you get started with Actions

name: Build and publish release

# Controls when the workflow will run
on:
  push:
    tags:
      - 'v*'

#   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-themes:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: install zip
        run: sudo apt-get install zip

      # delete dist folder
      - name: delete dist folder
        run: rm -rf dist

      - name: install node js 19
        uses: actions/setup-node@v1
        with:
          node-version: '19'

      - name: install dependencies after cd into themes
        run: |
          cd themes
          npm install

      - name: run the build.js script in the root
        run: |
          cd themes
          node build.js
          # Runs a set of commands using the runners shell
      # zip -r frappe.zip frappe
      # zip each folder in built directly so there is no ghost directory then move it to themes/dist
      - name: zip each theme (frappe, latte, macchiato, mocha)
        run: |
          cd themes
          cd built
          for d in */ ; do
            zip -r $d.zip $d
            mv $d.zip ../dist
          done

      # draft a release then publish the dist as the files
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: themes/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
