name: Build and publish release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:


jobs:
  build-themes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install zip
        run: sudo apt-get install zip

      # delete dist folder
      - name: delete dist folder
        run: rm -rf themes/dist

      - name: install node js 19
        uses: actions/setup-node@v1
        with:
          node-version: '19'

      - name: install dependencies after cd into themes
        run: |
          cd themes
          npm install

      - name: run the build.js script in the root
        run: |
          cd themes
          node build.js
          # Runs a set of commands using the runners shell
      # zip -r frappe.zip frappe
      # zips each folder in built directly so there is no ghost directory then move it to themes/dist
      - name: zip each theme (frappe, latte, macchiato, mocha)
        run: |
          cd themes
          mkdir dist
          cd built
          for theme in frappe latte macchiato mocha; do
            zip -r $theme.zip $theme
            mv $theme.zip ../dist/
          done

      # draft a release then publish the dist as the files
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: themes/dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
